version: '3.8'

services:
  # database
  postgresql-db:
    image: postgres:alpine
    networks:
      - oop-infra
    volumes:
      - app-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres@123
      - POSTGRES_DATABASE=OnlineClothe

  pgbouncer:
    image: bitnami/pgbouncer
    networks:
      - oop-infra
    ports:
      - "6432:6432"
    environment:
      - POSTGRESQL_HOST=postgresql-db
      - POSTGRESQL_PORT=5432
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres@123
      - POSTGRESQL_DATABASE=OnlineClothe
      - PGBOUNCER_PORT=6432
      - PGBOUNCER_BIND_ADDRESS=0.0.0.0
      - PGBOUNCER_EXTRA_FLAGS=--verbose
      - PGBOUNCER_DATABASE=OnlineClothe
      - PGBOUNCER_DEFAULT_POOL_SIZE=50

  mail-server-smtp:
    image: marcopas/docker-mailslurper
    networks:
      - oop-infra
    ports:
      - "2500:2500"
      - "8080:8080"
      - "8085:8085"

networks:
  oop-infra:
  oop-app:


volumes:
  app-data:
